### PR TITLE
Rename VERSION to CPS_VERSION

### PR DESCRIPTION
**Pull request by ckyang0225**
The `VERSION` file introduced from https://github.com/cps-org/cps-config/commit/cc40978ecf88e8ca194881ba333323f734143f95 caused meson build fail.
This PR fixed it by renaming `VERSION` file to `CPS_VERSION`.
Also verified all tests passed now, and CI passes, too.

Before:
```
ninja: Entering directory `builddir'
[1/16] Compiling C++ object src/libcps.a.p/cps_env.cpp.o
[2/16] Compiling C++ object loader_test.p/tests_loader.cpp.o
FAILED: loader_test.p/tests_loader.cpp.o
c++ -Iloader_test.p -I. -I.. -Isrc -I../src -I/opt/homebrew/Cellar/googletest/1.14.0/include -I/opt/homebrew/Cellar/fmt/10.2.1_1/include -I/opt/homebrew/include -I/opt/homebrew/share -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_ASSERTIONS=1 -Wall -Winvalid-pch -Wextra -std=c++17 -O2 -g -DGTEST_HAS_PTHREAD=1 -MD -MQ loader_test.p/tests_loader.cpp.o -MF loader_test.p/tests_loader.cpp.o.d -o loader_test.p/tests_loader.cpp.o -c ../tests/loader.cpp
In file included from ../tests/loader.cpp:6:
In file included from ../src/cps/loader.hpp:7:
In file included from ../src/cps/version.hpp:7:
In file included from /opt/homebrew/include/tl/expected.hpp:23:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/exception:82:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__exception/exception_ptr.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__exception/operations.h:14:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:41:
../version:1:1: error: expected unqualified-id
0.0.1
^
```

After:
```
ninja: Entering directory `builddir'
[6/16] Compiling C++ object loader_test.p/tests_loader.cpp.o
In file included from ../tests/loader.cpp:7:
/opt/homebrew/Cellar/googletest/1.14.0/include/gtest/gtest.h:1379:11: warning: comparison of integers of different signs: 'const unsigned long' and 'const int' [-Wsign-compare]
  if (lhs == rhs) {
      ~~~ ^  ~~~
/opt/homebrew/Cellar/googletest/1.14.0/include/gtest/gtest.h:1398:12: note: in instantiation of function template specialization 'testing::internal::CmpHelperEQ<unsigned long, int>' requested here
    return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
           ^
../tests/loader.cpp:239:13: note: in instantiation of function template specialization 'testing::internal::EqHelper::Compare<unsigned long, int, nullptr>' requested here
            ASSERT_EQ(package->components.size(), 7) << "should have found 7 different components";
            ^
/opt/homebrew/Cellar/googletest/1.14.0/include/gtest/gtest.h:1898:31: note: expanded from macro 'ASSERT_EQ'
#define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
                              ^
/opt/homebrew/Cellar/googletest/1.14.0/include/gtest/gtest.h:1882:54: note: expanded from macro 'GTEST_ASSERT_EQ'
  ASSERT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
                                                     ^
1 warning generated.
[15/16] Running all tests.
1/5 loader                          OK              0.21s
2/5 version                         OK              0.35s
3/5 utils                           OK              0.52s
4/5 pkg-config compatibility        OK              0.74s   9 subtests passed
5/5 cps integration tests           OK              0.75s   20 subtests passed

Ok:                 5
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0
```

### CODE REVIEW

**Comment by ckyang0225** [comment]
@bretbrownjr @lunacd @dcbaker Please take a look, thanks

**Comment by ckyang0225** [comment]
> @ckyang0225 or @dcbaker... can someone educate me about the filename VERSION confuses Meson?

tbh I'm not meson expert but just observed this issue and tried to fix.
@dcbaker might answer it better I believe.

**Review by bretbrownjr — APPROVED** [review]
It fixes things, so I'll merge. Happy to revisit with @dcbaker if we missed something.

**Comment by dcbaker** [comment]
Ah, I have an idea of what's going on. Meson by default includes the local directory, both source and build. I'll send out a followup to see if that fixes things.

**Pull request merged**
