### PR TITLE
editorconfig: define the configuration that is already in use for toml

### PR DESCRIPTION
**Pull request by dcbaker**

### CODE REVIEW

**Comment by bretbrownjr** [comment]
Definitely. I don't even know what toml this issue might be referring to.

**Comment by dcbaker** [comment]
There is a little test runner that uses a toml description of test cases: https://github.com/cps-org/cps-config/blob/main/tests/cases.toml

**Comment by bretbrownjr** [comment]
Ah. I saw that since I asked.

Can we use pedantic or something to just dump a schema?

**Comment by dcbaker** [comment]
We could do that, but that’s orthogonal. All editorconfig is is a cross editor standard for setting things like indent size, indent style. There’s a vscode plugin I’m using, but there’s a lot of supported editors. In this case what’s happening is setting the indent in toml files to 2 spaces instead of the default 4 used in c++ files

**Review by bretbrownjr — APPROVED** [review]
I have no opinions on .editorconfig yet, but this seems benign, so I want to merge this and move on.

**Pull request merged**
