### PR TITLE
loader: use template specialization instead of multiple functions

### PR DESCRIPTION
**Pull request by dcbaker**
It just looks cleaner to me

### CODE REVIEW

**Review by bretbrownjr — APPROVED** [review]
Sure, why not?

Note that you could also use [tagged dispatch](https://iamsorush.com/posts/cpp-tag-dispatch/) to construct an overload set instead. That would give you nicer looking error messages, arguably nicer syntax (angle brackets are hard on the eyes), and have the same upsides that you have here.

**Comment by bretbrownjr** [comment]
@dcbaker How are you feeling about this one? You could always land it and let someone else fiddle with tag dispatch if they care.

**Comment by dcbaker** [comment]
I looked at tagged dispatch a bit and got something working, but felt like the end result was worse than either what's in main now or this, so I think my preference would be to merge this now as-is unless and someone else can follow up with tagged dispatch to see if that looks better than what we already have.

**Review by bretbrownjr — APPROVED** [review]
Fair enough. Let's keep the momentum then.

**Comment by bretbrownjr** [comment]
@dcbaker Looks like we have conflicts blocking this one.

**Pull request merged**
