### PR TITLE
Switch to nlohmann json

### PR DESCRIPTION
**Pull request by lunacd**
nlohmann json is better maintained and has a better project setup that allows it to be consumed with less effort, at least on the CMake side. In contrast, jsoncpp only has 2 commits since 2023.

According to a rather dated benchmark [1], nlohmann json has better JSON standard conformance, e.g. no trailing comma, than jsoncpp and has better performance. Although this benchmark was conducted a while back, jsoncpp hasn't been significantly updated for a long while. I'd be surprised if the numbers would move in jsoncpp's favor.

[1] https://github.com/miloyip/nativejson-benchmark

### CODE REVIEW

**Comment by lunacd** [comment]
Hmm, I thought Pixi just calls meson.  But looks like it does something different

**Comment by dcbaker** [comment]
This seems fine to me, although I'd really like to land #97 first, since I know that works with jsoncpp, and fixes the bogus test.

**Comment by dcbaker** [comment]
Since #97 landed (thanks for the review!), can you rebase this on main? Once that's done I'd be happy to merge this.

**Comment by lunacd** [comment]
Rebased and it seems to have passed :)

**Review by dcbaker — APPROVED** [review]

**Comment by dcbaker** [comment]
LGTM, merged.

**Pull request merged**
