### PR TITLE
Use build system libdir

### PR DESCRIPTION
**Pull request by dcbaker**
Instead of hardcoding it.

This required some enhancements to our test system, and that we generate tests that need to use `@prefix@`, since the `{lib}` component depends on how the build is configured. I've also done some work to make the handling of the libdir and the datadir more robust (ie, only remove one, fail if we can't remove all components).

This does, I noticed, use `datadir` instead of harding coding `share` as the datadir path. That might not actually be desirable.

~~Based on #93~~
~~Based on #102~~

### CODE REVIEW

**Comment by dcbaker** [comment]
Ah, I'm kinda surprised pixi is the only thing catch that bug. I'll send out a v2 later to fix that.

**Comment by dcbaker** [comment]
The remaining test failure is really annoying, because it only exists in our test configuration, since we have hardcoded paths, but those paths need to depend on the configured libdir.

**Review by tylerjw — COMMENTED** [review]
When I try to build and test this locally I get this build failure:

```
[2/12] Compiling C++ object src/libcps.a.p/cps_printer.cpp.o
FAILED: src/libcps.a.p/cps_printer.cpp.o 
c++ -Isrc/libcps.a.p -Isrc -I../src -I../subprojects/nlohmann_json-3.11.2/single_include -I../subprojects/expected-1.1.0/include -Isrc/cps/pc_compat -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O2 -g -fPIC -Werror=shadow -Werror=implicit-fallthrough -MD -MQ src/libcps.a.p/cps_printer.cpp.o -MF src/libcps.a.p/cps_printer.cpp.o.d -o src/libcps.a.p/cps_printer.cpp.o -c ../src/cps/printer.cpp
../src/cps/printer.cpp: In function ‘int cps::printer::pkgconf(const cps::search::Result&, const Config&)’:
../src/cps/printer.cpp:88:33: error: ‘join’ is not a member of ‘fmt’
   88 |         fmt::print("{}\n", fmt::join(args, " "));
      |                                 ^~~~
[6/12] Compiling C++ object src/libcps.a.p/cps_search.cpp.o
ninja: build stopped: subcommand failed.
```

I'm not sure what could be causing this.

**Comment by tylerjw** [comment]
I see that it found version 11.0.2 of fmt. Is that the wrong version?

**Comment by tylerjw** [comment]
I hid my own comment as I checked PR 94 instead of PR 95 and the issue I found is unrelated. This branch builds and tests just fine.

**Review by tylerjw — APPROVED** [review]

**Pull request merged**
