### PR TITLE
Rerun actions on workflow changes

### PR DESCRIPTION
**Pull request by lunacd**
A previous commit [1] was made to limit when the tests are run. However,
the list in [1] does not include the workflow file itself. This
prevents tests from being executed if a commit or PR only modifies
test.yml workflow file. That is, without this change, this very PR would
not trigger any testing.

[1] https://github.com/cps-org/cps-config/commit/b901168e1617fd5c15f30a65b62126fda594339b

### CODE REVIEW

**Review by bretbrownjr — CHANGES_REQUESTED** [review]
Makes sense to me, I think, but *some* commit message is a good idea even for little changes. For instance, what happened before this commit that made this an interesting change to make?

**Comment by dcbaker** [comment]
Also, should we watch the docket files as well?

**Comment by lunacd** [comment]
- Added commit description
- Restricted path from `.github/workflows/**` to `.github/workflows/test.yml`. The testing workflow does not need to rerun if a commit modifies the other workflows.

> Also, should we watch the docket files as well?

Dockerfiles currently live in `tests/`. If they were to move to somewhere else, then we should take care to include them as well.

**Review by dcbaker — APPROVED** [review]

**Comment by dcbaker** [comment]
@bretbrownjr, do you have any more concerns about this, or are you happy to merge this?

**Review by bretbrownjr — APPROVED** [review]

**Comment by bretbrownjr** [comment]
GitHub says there are merge conflicts though. I might get to that at some point, but someone feel free to beat me to it.

**Comment by lunacd** [comment]
It's because of the recent addition of the `VERSION` file. Resolved

**Review by tylerjw — APPROVED** [review]

**Comment by bretbrownjr** [comment]
Merged https://github.com/cps-org/cps-config/commit/7575fd7f24bd2669fa886479f4b155036bf08d04 via the git CLI in the interest of landing this simple change efficiently and not drawing this PR out even more.

**Pull request closed without merging**
